package com.example.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.stockx.bean.SettingBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SETTING_BEAN".
*/
public class SettingBeanDao extends AbstractDao<SettingBean, Long> {

    public static final String TABLENAME = "SETTING_BEAN";

    /**
     * Properties of entity SettingBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property CurrentAccountID = new Property(1, long.class, "currentAccountID", false, "CURRENT_ACCOUNT_ID");
    }


    public SettingBeanDao(DaoConfig config) {
        super(config);
    }
    
    public SettingBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SETTING_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"CURRENT_ACCOUNT_ID\" INTEGER NOT NULL );"); // 1: currentAccountID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SETTING_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SettingBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getCurrentAccountID());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SettingBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getCurrentAccountID());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public SettingBean readEntity(Cursor cursor, int offset) {
        SettingBean entity = new SettingBean( //
            cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1) // currentAccountID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SettingBean entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setCurrentAccountID(cursor.getLong(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SettingBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SettingBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SettingBean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
